class ProcessoPlataformaModel:
    def __init__(self, plp_prc_id=None,
                 plp_plt_id=None,
                 plp_numero=None,
                 plp_status=None,
                 plp_comarca=None,
                 plp_serventia=None,
                 plp_juizo=None,
                 plp_fase=None,
                 plp_diligencia=None,
                 plp_vara=None,
                 plp_filtro=None,
                 plp_penhora=None,
                 plp_valor_causa=None,
                 plp_valor_condenacao=None,
                 plp_classe=None,
                 plp_assunto=None,
                 plp_processo_origem=None,
                 plp_data_distribuicao=None,
                 plp_data_transito_julgado=None,
                 plp_codigo=None,
                 plp_segredo=None,
                 plp_efeito_suspensivo=None,
                 plp_prioridade=None,
                 plp_localizado=None,
                 plp_migrado=None,
                 plp_grau=None,
                 plp_data_update=None):

        self.plp_prc_id = plp_prc_id
        self.plp_plt_id = plp_plt_id
        self.plp_numero = plp_numero
        self.plp_status = plp_status
        self.plp_comarca = plp_comarca
        self.plp_serventia = plp_serventia
        self.plp_juizo = plp_juizo
        self.plp_fase = plp_fase
        self.plp_diligencia = plp_diligencia
        self.plp_vara = plp_vara
        self.plp_filtro = plp_filtro
        self.plp_penhora = plp_penhora
        self.plp_valor_causa = plp_valor_causa
        self.plp_valor_condenacao = plp_valor_condenacao
        self.plp_classe = plp_classe
        self.plp_assunto = plp_assunto
        self.plp_processo_origem = plp_processo_origem
        self.plp_data_distribuicao = plp_data_distribuicao
        self.plp_data_transito_julgado = plp_data_transito_julgado
        self.plp_codigo = plp_codigo
        self.plp_segredo = plp_segredo
        self.plp_efeito_suspensivo = plp_efeito_suspensivo
        self.plp_prioridade = plp_prioridade
        self.plp_localizado = plp_localizado
        self.plp_migrado = plp_migrado
        self.plp_grau = plp_grau
        self.plp_data_update = plp_data_update